/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import jdbc.Connexion;

/**
 *
 * @author macbook
 */
public class Authentification extends javax.swing.JFrame {
    private int IdEmp;
    Connexion con = new Connexion();
    Connection Maconnexion;
    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
        Maconnexion = con.getMaconnexion();
        Admincon.setVisible(false);
        ConAdmin.setVisible(false);
    }
    public int getId(){
        return IdEmp=-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConEmploye = new javax.swing.JButton();
        Idcon = new javax.swing.JTextField();
        ConAdmin = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mdpcon = new javax.swing.JPasswordField();
        Admincon = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConEmploye.setText("Connexion");
        ConEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConEmployeActionPerformed(evt);
            }
        });

        Idcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdconActionPerformed(evt);
            }
        });

        ConAdmin.setText("Connexion");
        ConAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConAdminActionPerformed(evt);
            }
        });

        AdminButton.setText("ADMINISTRATEUR");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Identifient");

        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Admincon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConAdmin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Mdpcon, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(Idcon))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(AdminButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConEmploye)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AdminButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConAdmin)
                    .addComponent(Admincon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Mdpcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(ConEmploye)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdconActionPerformed

    private void ConAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConAdminActionPerformed
        if(!Admincon.getText().isEmpty())
        {
            if(Admincon.getText().equalsIgnoreCase("ADMIN") )
            {
                JOptionPane.showMessageDialog(null ,"Admin connectée avec succée !! " );
                dispose();
                EspaceAdmin Ea=new EspaceAdmin();
                Ea.setSize(1300, 500);
                GUI G=new GUI();
                G.add(Ea);
                G.setVisible(true);
                G.setSize(1300, 500);
            }
            else
            {
                JOptionPane.showMessageDialog(null ,"Mot de passe incorrecte !! ","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        else {JOptionPane.showMessageDialog(null ," Veuillez remplir le champ mot de passe  !! ","Warning",JOptionPane.WARNING_MESSAGE); }
    }//GEN-LAST:event_ConAdminActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        Admincon.setVisible(true);
        ConAdmin.setVisible(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void ConEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConEmployeActionPerformed
        ResultSet Rs = null, Rs1=null ;
        Statement St , St1;
        try {
            St=Maconnexion.createStatement();
            if(Idcon.getText().isEmpty() && Mdpcon.getText().isEmpty())
            {JOptionPane.showMessageDialog(null ," Veuillez remplir les champs !! ","Warning",JOptionPane.WARNING_MESSAGE);}
            else
            {if(!Idcon.getText().isEmpty())
                {
                    if(!Mdpcon.getText().isEmpty())
                    { Rs=St.executeQuery("select ID from employe where ID='"+Idcon.getText()+"' and Password='"+Mdpcon.getText()+"'");
                        if(Rs.first())
                        {
                            int id = Rs.getInt(1);
                            St1=Maconnexion.createStatement();
                            Rs1=St1.executeQuery("select Poste from employe where ID='"+id+"'");
                            if(Rs1.first()){
                            switch(Rs1.getString(1))
                            {
                                case "Chef" :
                                    JOptionPane.showMessageDialog(null ,"Bienvenue Chef !! " );
                                    dispose();
                                    EspaceChef Ec=new EspaceChef();
                                    Ec.setSize(1300, 500);
                                    GUI G1=new GUI();
                                    G1.add(Ec);
                                    G1.setVisible(true);
                                    G1.setSize(1300, 500);
                                    break;
                                case "Directeur":
                                    JOptionPane.showMessageDialog(null ,"Bienvenidos BOSS!! " );
                                    dispose();
                                    EspaceDirecteur Ed=new EspaceDirecteur();
                                    Ed.setSize(1300, 500);
                                    GUI G2=new GUI();
                                    G2.add(Ed);
                                    G2.setVisible(true);
                                    G2.setSize(1300, 800);
                                    break;
                                default : 
                                    JOptionPane.showMessageDialog(null ,"Bienvenue !! " );
                                    dispose();
                                    EspaceEmploye Ee=new EspaceEmploye();
                                    Ee.setSize(1300, 500);
                                    GUI G3=new GUI();
                                    G3.add(Ee);
                                    G3.setVisible(true);
                                    G3.setSize(1300, 800);
                                    break;
                            }
                            }
                        }
                        else
                        {JOptionPane.showMessageDialog(null ,"Id ou mdp incorrect !! " ,"Warning",JOptionPane.WARNING_MESSAGE);}
                    }
                    else
                    {JOptionPane.showMessageDialog(null ," Veuillez remplir le champ mot de passe  !! ","Warning",JOptionPane.WARNING_MESSAGE);}
                }
                else
                {JOptionPane.showMessageDialog(null ," Veuillez remplir le champ identifiant  !! ","Warning",JOptionPane.WARNING_MESSAGE);}
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null ,"Probléme dans le requete de connexion  !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ConEmployeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JPasswordField Admincon;
    private javax.swing.JButton ConAdmin;
    private javax.swing.JButton ConEmploye;
    private javax.swing.JTextField Idcon;
    private javax.swing.JPasswordField Mdpcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
