/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import jdbc.Connexion;

/**
 *
 * @author Sarah LOTFI
 */
public class Authentify extends javax.swing.JPanel {
   Connexion con = new Connexion();
   Connection Maconnexion;
    /**
     * Creates new form Authentify
     */
    public Authentify() {
        initComponents();
        Maconnexion = con.getMaconnexion();
        Admincon.setVisible(false);
        ConAdmin.setVisible(false);
        Mdpcon.setVisible(false);
        Idcon.setVisible(false);
        jButton2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Authentify = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ConAdmin = new javax.swing.JButton();
        Admincon = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Idcon = new javax.swing.JTextField();
        Mdpcon = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        Authentify.setLayout(null);

        AdminButton.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        AdminButton.setText("Administrateur");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });
        Authentify.add(AdminButton);
        AdminButton.setBounds(90, 30, 180, 90);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("    Utilisateurs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Authentify.add(jButton1);
        jButton1.setBounds(340, 30, 180, 90);

        ConAdmin.setToolTipText("");
        ConAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConAdminActionPerformed(evt);
            }
        });
        Authentify.add(ConAdmin);
        ConAdmin.setBounds(110, 220, 150, 30);

        Admincon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminconActionPerformed(evt);
            }
        });
        Authentify.add(Admincon);
        Admincon.setBounds(100, 160, 170, 30);

        jLabel1.setText("Identifiant");
        Authentify.add(jLabel1);
        jLabel1.setBounds(320, 140, 76, 20);

        jLabel2.setText("Mot de passe");
        Authentify.add(jLabel2);
        jLabel2.setBounds(320, 180, 76, 20);

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Authentify.add(jButton2);
        jButton2.setBounds(350, 220, 150, 30);
        Authentify.add(Idcon);
        Idcon.setBounds(400, 140, 119, 26);
        Authentify.add(Mdpcon);
        Mdpcon.setBounds(400, 180, 120, 26);
        Authentify.add(jLabel5);
        jLabel5.setBounds(10, -10, 620, 310);

        add(Authentify);
        Authentify.setBounds(-10, 200, 620, 770);
        add(jLabel3);
        jLabel3.setBounds(0, 0, 882, 202);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        // TODO add your handling code here:
        Admincon.setVisible(true);
        ConAdmin.setVisible(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ResultSet Rs = null, Rs1=null ;
        Statement St , St1;
        try {
            St=Maconnexion.createStatement();
            if(Idcon.getText().isEmpty() && Mdpcon.getText().isEmpty())
            {JOptionPane.showMessageDialog(null ," Veuillez remplir tous les champs !! ","Warning",JOptionPane.WARNING_MESSAGE);}
            else
            {if(!Idcon.getText().isEmpty())
                {
                    if(!Mdpcon.getText().isEmpty())
                    { Rs=St.executeQuery("select ID from employe where ID='"+Idcon.getText()+"' and Password='"+Mdpcon.getText()+"'");
                        if(Rs.first())
                        {
                            int id = Rs.getInt(1);
                            St1=Maconnexion.createStatement();
                            Rs1=St1.executeQuery("select Poste from employe where ID='"+id+"'");
                            if(Rs1.first()){
                                    SwingUtilities.getWindowAncestor(this).dispose();
                                    JOptionPane.showMessageDialog(null ," Bienvenidos "+Rs1.getString(1)+" !!");
                                    GUI G2=new GUI();
                                    EspaceDirecteur Ed =new EspaceDirecteur(id);
                                    Ed.setSize(1000, 500);
                                    G2.add(Ed);
                                    G2.setSize(1000, 500);
                                    G2.setVisible(true);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null ,"Id ou mdp incorrect !! " ,"Warning",JOptionPane.WARNING_MESSAGE);}
                    }else{
                        JOptionPane.showMessageDialog(null ," Veuillez remplir le champ mot de passe  !! ","Warning",JOptionPane.WARNING_MESSAGE);}
                }else{
                JOptionPane.showMessageDialog(null ," Veuillez remplir le champ identifiant  !! ","Warning",JOptionPane.WARNING_MESSAGE);}
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null ,"Probléme dans le requete de connexion  !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ConAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConAdminActionPerformed
        
        if(!Admincon.getText().isEmpty())
        {
            if(Admincon.getText().equalsIgnoreCase("ADMIN") )
            {
                SwingUtilities.getWindowAncestor(this).dispose();
                JOptionPane.showMessageDialog(null ,"Admin connectée avec succée !! " );
                GUI G=new GUI();
                G.setSize(1000, 500);
                EspaceAdmin Ea= new EspaceAdmin();
                Ea.setSize(1000, 500);
                G.add(Ea);
                G.setVisible(true);                
            }
            else
            {
                JOptionPane.showMessageDialog(null ,"Mot de passe incorrecte !! ","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        else {JOptionPane.showMessageDialog(null ," Veuillez remplir le champ mot de passe  !! ","Warning",JOptionPane.WARNING_MESSAGE); }
    }//GEN-LAST:event_ConAdminActionPerformed

    private void AdminconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminconActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mdpcon.setVisible(true);
        Idcon.setVisible(true);
        jButton2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JPasswordField Admincon;
    private javax.swing.JPanel Authentify;
    private javax.swing.JButton ConAdmin;
    private javax.swing.JTextField Idcon;
    private javax.swing.JPasswordField Mdpcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
