/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import event.management.Admin;
import event.management.Dept;
import event.management.Employe;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import jdbc.Connexion;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sarah LOTFI
 */
public class EspaceAdmin extends javax.swing.JPanel {
    /**
     * Creates new form EspaceAdmin
     */
    Connexion con = new Connexion();
    private Connection  Maconnexion;
    
    
    public EspaceAdmin() {
        initComponents();
        Maconnexion = con.getMaconnexion();
        updateJTable5_Employe("Id");
        updateJTable6_Departement();
        ModifierEmploye.setEnabled(false);
        DeleteEmploye.setEnabled(false);
        jButton20.setEnabled(false);
        jButton21.setEnabled(false);
        jPanel3.setVisible(false);
        RemplirComboboxDepartement();
    }
    
    public void updateJTable5_Employe(String critere){
        Statement St;
        ResultSet Rs=null;
        TableEmploye.removeAll();
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select ID, Nom, Prenom, Poste, NomDept departement from employe, departement where (employe.IDdept=departement.IDdept ) order by "+critere+" ");
            TableEmploye.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null ,"Problème dans la sélection des Employés !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
    public void updateJTable6_Departement(){
        Statement St;
        ResultSet Rs=null;
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select * from departement;");
            jTable6.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null ,"Problème dans la sélection des départements !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public  void RemplirComboboxDepartement(){
        Statement St;
        ResultSet Rs=null;
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select distinct NomDept from departement;");
            while(Rs.next()){
                comboBox_departement.addItem(Rs.getString("NomDept"));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null ,"Problème dans la sélection des départements dans ComboBox!! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EspaceAdmin2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        ButtonAjoutDept = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextDept = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        SearchText = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableEmploye = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        TriEmp2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        DeleteEmploye = new javax.swing.JButton();
        ModifierEmploye = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Text_PrenomEmploye = new javax.swing.JTextField();
        Text_PosteEmploye = new javax.swing.JTextField();
        AddEmploye = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Text_PwdEmploye = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Text_NomEmploye = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboBox_departement = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Disconnect2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 900));
        setLayout(null);

        EspaceAdmin2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nom département"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);

        ButtonAjoutDept.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ButtonAjoutDept.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\ajouter dept.png")); // NOI18N
        ButtonAjoutDept.setText("Ajouter département");
        ButtonAjoutDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjoutDeptActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\seo-social-web-network-internet_262_icon-icons.com_61518.png")); // NOI18N
        jButton20.setText("Supprimer");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\modif.png")); // NOI18N
        jButton21.setText("Modifier");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jTextDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeptActionPerformed(evt);
            }
        });
        jTextDept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDeptKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonAjoutDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextDept))))
                .addGap(152, 152, 152))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(ButtonAjoutDept)
                        .addGap(26, 26, 26)
                        .addComponent(jTextDept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Section départements", jPanel12);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        SearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchTextKeyTyped(evt);
            }
        });
        jPanel10.add(SearchText);
        SearchText.setBounds(400, 10, 110, 30);

        TableEmploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom", "Poste", "Département"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableEmploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEmployeMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TableEmploye);

        jPanel10.add(jScrollPane5);
        jScrollPane5.setBounds(12, 51, 550, 190);

        jButton16.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\ajouter emp.png")); // NOI18N
        jButton16.setText("Ajouter employé");
        jButton16.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton16);
        jButton16.setBounds(590, 10, 230, 60);

        TriEmp2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        TriEmp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nom", "Prenom", "Departement", "Poste" }));
        TriEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriEmp2ActionPerformed(evt);
            }
        });
        jPanel10.add(TriEmp2);
        TriEmp2.setBounds(190, 10, 113, 30);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Trier les employés par: ");
        jPanel10.add(jLabel8);
        jLabel8.setBounds(10, 20, 173, 17);

        DeleteEmploye.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        DeleteEmploye.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\seo-social-web-network-internet_262_icon-icons.com_61518.png")); // NOI18N
        DeleteEmploye.setText("Supprimer");
        DeleteEmploye.setPreferredSize(new java.awt.Dimension(71, 30));
        DeleteEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeActionPerformed(evt);
            }
        });
        jPanel10.add(DeleteEmploye);
        DeleteEmploye.setBounds(280, 260, 140, 40);

        ModifierEmploye.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ModifierEmploye.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\modif.png")); // NOI18N
        ModifierEmploye.setText("Modifier");
        ModifierEmploye.setPreferredSize(new java.awt.Dimension(71, 30));
        ModifierEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierEmployeActionPerformed(evt);
            }
        });
        jPanel10.add(ModifierEmploye);
        ModifierEmploye.setBounds(70, 260, 140, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Nom");

        AddEmploye.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        AddEmploye.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\check-mark-3-512 png.png")); // NOI18N
        AddEmploye.setText("Valider");
        AddEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Prénom");

        Text_PwdEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_PwdEmployeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setText("Poste");

        Text_NomEmploye.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        comboBox_departement.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        comboBox_departement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Departement" }));
        comboBox_departement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBox_departementMouseClicked(evt);
            }
        });
        comboBox_departement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_departementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_PosteEmploye)
                            .addComponent(Text_PrenomEmploye)
                            .addComponent(Text_PwdEmploye)
                            .addComponent(Text_NomEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddEmploye)
                            .addComponent(comboBox_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_NomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_PrenomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_PosteEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_PwdEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(comboBox_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel10.add(jPanel3);
        jPanel3.setBounds(590, 70, 230, 280);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("Trier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);
        jButton1.setBounds(320, 10, 70, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\icone_search (1).png")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel10.add(jLabel6);
        jLabel6.setBounds(520, 10, 30, 30);

        jTabbedPane3.addTab("Section Employés", jPanel10);

        Disconnect2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Disconnect2.setText("Déconnexion");
        Disconnect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disconnect2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EspaceAdmin2Layout = new javax.swing.GroupLayout(EspaceAdmin2);
        EspaceAdmin2.setLayout(EspaceAdmin2Layout);
        EspaceAdmin2Layout.setHorizontalGroup(
            EspaceAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EspaceAdmin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Disconnect2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        EspaceAdmin2Layout.setVerticalGroup(
            EspaceAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspaceAdmin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Disconnect2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(EspaceAdmin2);
        EspaceAdmin2.setBounds(0, 230, 860, 584);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\empppp - Copie.png")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(900, 239));
        jLabel5.setMinimumSize(new java.awt.Dimension(900, 239));
        jLabel5.setPreferredSize(new java.awt.Dimension(900, 239));
        add(jLabel5);
        jLabel5.setBounds(80, 0, 840, 230);
    }// </editor-fold>//GEN-END:initComponents

    private void Disconnect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disconnect2ActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        JOptionPane.showMessageDialog(null ,"Au revoir !! " );
        GUI G=new GUI();
        Authentify A=new Authentify();
        A.setSize(1300, 500);
        G.add(A);
        G.setSize(600, 559);
        G.setVisible(true);
    }//GEN-LAST:event_Disconnect2ActionPerformed

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        jButton20.setEnabled(true);
        jButton21.setEnabled(true);
    }//GEN-LAST:event_jTable6MouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Admin A=new Admin();
        A.SupprimerD((int) jTable6.getModel().getValueAt(jTable6.getSelectedRow(),0));
        updateJTable6_Departement();
        comboBox_departement.removeItem(jTextDept.getText());
        jButton20.setEnabled(false);
        jButton21.setEnabled(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void ButtonAjoutDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjoutDeptActionPerformed
        if(jTextDept.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "La case est vide débil " ,"Attention !!" , JOptionPane.WARNING_MESSAGE );
        }else{
            Admin A=new Admin();
            A.AjouterD(jTextDept.getText());
            comboBox_departement.addItem(jTextDept.getText());
            jTextDept.setText("");
            updateJTable6_Departement();
        } 
    }//GEN-LAST:event_ButtonAjoutDeptActionPerformed

    private void jTextDeptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDeptKeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTextDept.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "La case est vide débil " ,"Attention !!" , JOptionPane.WARNING_MESSAGE );
            }else{
                Admin A=new Admin();
                A.AjouterD(jTextDept.getText());
                comboBox_departement.addItem(jTextDept.getText());
                jTextDept.setText("");
                updateJTable6_Departement();
            }  
        }
    }//GEN-LAST:event_jTextDeptKeyPressed

    private void ModifierEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierEmployeActionPerformed
        Admin A=new Admin();
        Dept D=new Dept();
        int Id=(int) TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),0);
        String nom=TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),1).toString();
        String prenom=TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),2).toString();
        String poste=TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),3).toString();
        String dept=TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),4).toString();
        A.ModifierE(Id , poste, nom, prenom, D.getIDdept(dept));
        JOptionPane.showMessageDialog(null, "Employé modifié avec succès");
        updateJTable5_Employe("Id");
        ModifierEmploye.setEnabled(false);
    }//GEN-LAST:event_ModifierEmployeActionPerformed

    private void DeleteEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmployeActionPerformed
        Admin A=new Admin();
            A.SupprimerE((int) TableEmploye.getModel().getValueAt(TableEmploye.getSelectedRow(),0));
            updateJTable5_Employe("Id");
            ModifierEmploye.setEnabled(false);
            DeleteEmploye.setEnabled(false);
    }//GEN-LAST:event_DeleteEmployeActionPerformed

    private void TableEmployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEmployeMouseClicked
        ModifierEmploye.setEnabled(true);
        DeleteEmploye.setEnabled(true);
    }//GEN-LAST:event_TableEmployeMouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void AddEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeActionPerformed
        Admin A= new Admin();
        Dept D= new Dept();
        if(   !Text_PwdEmploye.getText().isEmpty()
           && !Text_PosteEmploye.getText().isEmpty()
           && !Text_NomEmploye.getText().isEmpty()
           && !Text_PrenomEmploye.getText().isEmpty() ){
            if(Text_PosteEmploye.getText().equalsIgnoreCase("Chef")){
                if(D.getChef(comboBox_departement.getSelectedItem().toString()) ){
                A.AjouterE(Text_PwdEmploye.getText(), Text_PosteEmploye.getText(), Text_NomEmploye.getText(), Text_PrenomEmploye.getText(),comboBox_departement.getSelectedItem().toString());
            }
            }else{
                                A.AjouterE(Text_PwdEmploye.getText(), Text_PosteEmploye.getText(), Text_NomEmploye.getText(), Text_PrenomEmploye.getText(),comboBox_departement.getSelectedItem().toString());
            }
            
        }else{
            JOptionPane.showMessageDialog(null ," Une case est vide débil " ,"Warning",JOptionPane.WARNING_MESSAGE); 
        }
        updateJTable5_Employe("Id");
    }//GEN-LAST:event_AddEmployeActionPerformed

    private void comboBox_departementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_departementActionPerformed

    }//GEN-LAST:event_comboBox_departementActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void TriEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriEmp2ActionPerformed

    }//GEN-LAST:event_TriEmp2ActionPerformed

    private void Text_PwdEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_PwdEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_PwdEmployeActionPerformed

    private void comboBox_departementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBox_departementMouseClicked
//        RemplirComboboxDepartement();
    }//GEN-LAST:event_comboBox_departementMouseClicked

    private void jTextDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateJTable5_Employe(TriEmp2.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyTyped
        String S=SearchText.getText();
        Statement St;
        ResultSet Rs=null;
        TableEmploye.removeAll();
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select ID, Nom, Prenom, Poste, Nomdept from employe , departement where (employe.IDdept=departement.IDdept) and (instr(ID,'"+S+"')<>0 or instr(Nom,'"+S+"')<>0 or instr(Prenom,'"+S+"')<>0 or instr(Nomdept,'"+S+"')<>0 )");
            TableEmploye.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null ,"Problème dans la sélection des Employés !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SearchTextKeyTyped

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmploye;
    private javax.swing.JButton ButtonAjoutDept;
    private javax.swing.JButton DeleteEmploye;
    private javax.swing.JButton Disconnect2;
    private javax.swing.JPanel EspaceAdmin2;
    private javax.swing.JButton ModifierEmploye;
    private javax.swing.JTextField SearchText;
    private javax.swing.JTable TableEmploye;
    private javax.swing.JTextField Text_NomEmploye;
    private javax.swing.JTextField Text_PosteEmploye;
    private javax.swing.JTextField Text_PrenomEmploye;
    private javax.swing.JTextField Text_PwdEmploye;
    private javax.swing.JComboBox TriEmp2;
    private javax.swing.JComboBox<String> comboBox_departement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextDept;
    // End of variables declaration//GEN-END:variables
}
