/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import jdbc.Connexion;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sarah LOTFI
 */
public class EspaceDirecteur extends javax.swing.JPanel {
        private int IdUser;

     Connexion con = new Connexion();
   Connection Maconnexion;
    /**
     * Creates new form EspaceDirecteur
     */
    public EspaceDirecteur(int Id) {
        initComponents();
        IdUser=Id;
        Maconnexion = con.getMaconnexion();
        switch(this.WhoAreYou()){
            case "Directeur":
                UpdateDirectorInterface();
                break;
            case "Chef" :
                JOptionPane.showMessageDialog(null, "probleme à 3chiri");
                UpdateChefInterface();
                break;
            default : 
                UpdateEmpoyeInterface();
                break;
        }
    }
    public String WhoAreYou(){
        Statement St;
        ResultSet Rs = null ;
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select Poste from Employe where Id="+IdUser+"");
            if(!Rs.first()){
                JOptionPane.showMessageDialog(null, "probleme à 3chiri");
            }else{
                return Rs.getString(1).toString();
            }
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null ,"Pb de generation votre interface !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
        return "";
    }
    public void UpdateEmpoyeInterface(){
        AffichagePane.setEnabledAt(4, true);
        UpdateTous();
        UpdatePublic();
        UpdatePrivate();
        UpdateParticipations();
    }
    public void UpdateChefInterface(){
        UpdateTous();
        UpdatePublic();
        UpdatePrivate();
        UpdateParticipations();
        UpdateMine();
    }
    public void UpdateDirectorInterface(){
        UpdateTousforDirector();
        UpdatePublicDirector();
        UpdatePrivateDirector();
        UpdateMineDirector();
        UpdateParticipations();
    }
    public void UpdateTousforDirector(){
        listeEvenement E=new listeEvenement(IdUser,"+","select * from event where IDEvent not in (select IDEvent from participations where IDEmp='"+IdUser+"')");
        TousPanel.add(E);
    }
    public void UpdatePublicDirector(){
//        listeEvenement E=new listeEvenement(IdUser,"+","  ");
//        PublicPanel.add(E);
    }
    public void UpdatePrivateDirector(){
//        listeEvenement E=new listeEvenement(IdUser,"+","");
//        PrivatePanel.add(E);
    }
    public void UpdateTous(){
        listeEvenement E=new listeEvenement(IdUser,"+","");
        TousPanel.add(E);
    }
    public void UpdatePublic(){
//        listeEvenement E=new listeEvenement(IdUser,"+","  ");
//        PublicPanel.add(E);
    }
    public void UpdatePrivate(){
//        listeEvenement E=new listeEvenement(IdUser,"+","");
//        PrivatePanel.add(E);
    }
    public void UpdateParticipations(){
//        listeEvenement E=new listeEvenement(IdUser,"-","");
//        ParticipationsPanel.add(E);
    }
    public void UpdateMineDirector(){
        listeEvenement E=new listeEvenement(IdUser,"*","select * from event  where IDOrg = '"+IdUser+"' ");
        MinePanel.add(E);
    }
    public void UpdateMine(){
//        listeEvenement E=new listeEvenement(IdUser,"Modifier","select e.IDEvent,Titre,Thème,Secteur,DateEvent,Lieu,Description,Type from event e,participations p where (e.IDEvent = p.IDEvent and IDOrg = "+IdUser+"); ");
//        MinePanel.add(E);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EspaceChef1 = new javax.swing.JPanel();
        AffichagePane = new javax.swing.JTabbedPane();
        TousPanel = new javax.swing.JPanel();
        PublicPanel = new javax.swing.JPanel();
        PrivatePanel = new javax.swing.JPanel();
        ParticipationsPanel = new javax.swing.JPanel();
        MinePanel = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        DiscoChef1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        CreatEventButton = new javax.swing.JButton();

        javax.swing.GroupLayout TousPanelLayout = new javax.swing.GroupLayout(TousPanel);
        TousPanel.setLayout(TousPanelLayout);
        TousPanelLayout.setHorizontalGroup(
            TousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        TousPanelLayout.setVerticalGroup(
            TousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Tous", TousPanel);

        javax.swing.GroupLayout PublicPanelLayout = new javax.swing.GroupLayout(PublicPanel);
        PublicPanel.setLayout(PublicPanelLayout);
        PublicPanelLayout.setHorizontalGroup(
            PublicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        PublicPanelLayout.setVerticalGroup(
            PublicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Publics", PublicPanel);

        javax.swing.GroupLayout PrivatePanelLayout = new javax.swing.GroupLayout(PrivatePanel);
        PrivatePanel.setLayout(PrivatePanelLayout);
        PrivatePanelLayout.setHorizontalGroup(
            PrivatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        PrivatePanelLayout.setVerticalGroup(
            PrivatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Privés", PrivatePanel);

        javax.swing.GroupLayout ParticipationsPanelLayout = new javax.swing.GroupLayout(ParticipationsPanel);
        ParticipationsPanel.setLayout(ParticipationsPanelLayout);
        ParticipationsPanelLayout.setHorizontalGroup(
            ParticipationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        ParticipationsPanelLayout.setVerticalGroup(
            ParticipationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Mes participations", ParticipationsPanel);

        javax.swing.GroupLayout MinePanelLayout = new javax.swing.GroupLayout(MinePanel);
        MinePanel.setLayout(MinePanelLayout);
        MinePanelLayout.setHorizontalGroup(
            MinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        MinePanelLayout.setVerticalGroup(
            MinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Mes événements", MinePanel);

        jTextField10.setText("Rechercher");

        DiscoChef1.setText("Déconnexion");
        DiscoChef1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscoChef1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Evénements");

        jLabel10.setText("Trier les événements par:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titre", "Secteur", "Thème", "Date", "Lieu", "Organisateur" }));

        CreatEventButton.setText("Créer un événement");
        CreatEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatEventButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EspaceChef1Layout = new javax.swing.GroupLayout(EspaceChef1);
        EspaceChef1.setLayout(EspaceChef1Layout);
        EspaceChef1Layout.setHorizontalGroup(
            EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspaceChef1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(DiscoChef1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EspaceChef1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AffichagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(CreatEventButton)
                        .addGap(79, 79, 79))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EspaceChef1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EspaceChef1Layout.setVerticalGroup(
            EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EspaceChef1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiscoChef1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AffichagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(CreatEventButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(EspaceChef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(EspaceChef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DiscoChef1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscoChef1ActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        JOptionPane.showMessageDialog(null ,"Au revoir!! BOSS " );
        GUI G=new GUI();
        Authentify A=new Authentify();
        A.setSize(1300, 500);
        G.add(A);
        G.setSize(500, 500);
        G.setVisible(true);
    }//GEN-LAST:event_DiscoChef1ActionPerformed

    private void CreatEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatEventButtonActionPerformed
        GUI G=new GUI();
        CreateEvent C=new CreateEvent(IdUser);
        C.setSize(1300, 500);
        G.add(C);
        G.setSize(500, 500);
        G.setVisible(true);
    }//GEN-LAST:event_CreatEventButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AffichagePane;
    private javax.swing.JButton CreatEventButton;
    private javax.swing.JButton DiscoChef1;
    private javax.swing.JPanel EspaceChef1;
    private javax.swing.JPanel MinePanel;
    private javax.swing.JPanel ParticipationsPanel;
    private javax.swing.JPanel PrivatePanel;
    private javax.swing.JPanel PublicPanel;
    private javax.swing.JPanel TousPanel;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField10;
    // End of variables declaration//GEN-END:variables
}
