/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import jdbc.Connexion;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sarah LOTFI
 */
public class EspaceDirecteur extends javax.swing.JPanel {
        private int IdUser;

     Connexion con = new Connexion();
   Connection Maconnexion;
    /**
     * Creates new form EspaceDirecteur
     */
    public EspaceDirecteur(int Id) {
        initComponents();
        IdUser=Id;
        Maconnexion = con.getMaconnexion();
        switch(this.WhoAreYou()){
            case "Directeur":
                UpdateDirectorInterface();
                break;
            case "Chef" :
                JOptionPane.showMessageDialog(null, "probleme à 3chiri");
                UpdateChefInterface();
                break;
            default : 
                UpdateEmpoyeInterface();
                break;
        }
    }
    public String WhoAreYou(){
        Statement St;
        ResultSet Rs = null ;
        try{
            St=Maconnexion.createStatement();
            Rs=St.executeQuery("select Poste from Employe where Id="+IdUser+"");
            if(!Rs.first()){
                JOptionPane.showMessageDialog(null, "probleme à 3chiri");
            }else{
                return Rs.getString(1).toString();
            }
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null ,"Pb de génération de votre interface !! "+ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
        return "";
    }
    public void UpdateEmpoyeInterface(){
        AffichagePane.setEnabledAt(4, false);
        CreatEventButton.setVisible(false);
        UpdateTous();
        UpdatePublic();
        UpdatePrivate();
        UpdateParticipations();
    }
    public void UpdateChefInterface(){
        UpdateTous();
        UpdatePublic();
        UpdatePrivate();
        UpdateParticipations();
        UpdateMine();
    }
    public void UpdateDirectorInterface(){
        UpdateTousforDirector();
        UpdatePublicDirector();
        UpdateMineDirector();
        UpdateParticipations();
    }
    public void UpdateTousforDirector(){
        listeEvenement E=new listeEvenement(IdUser,"+","select * from event where IDEvent not in (select IDEvent from participations where IDEmp='"+IdUser+"')");
        E.setSize(576, 360);
        TousPanel.add(E);
    }
    public void UpdatePublicDirector(){
        listeEvenement E=new listeEvenement(IdUser,"+"," select * from event where type = 'public' ");
        E.setSize(576, 360);
        PublicPanel.add(E);
    }
    public void UpdateTous(){
        listeEvenement E=new listeEvenement(IdUser,"+","select * from event where IDEvent not in (select IDEvent from participations where IDEmp = "+IdUser+")");
        E.setSize(576, 360);
        TousPanel.add(E);
    }
    public void UpdatePublic(){
        listeEvenement E=new listeEvenement(IdUser,"+","select * from event where type = 'public' ");
        E.setSize(576, 360); PublicPanel.add(E);
    }
    public void UpdatePrivate(){
        listeEvenement E=new listeEvenement(IdUser,"+","select * from event where IDEvent in (select IDEvent from eventdept where IDDept in (select IDDept from employe where ID = "+IdUser+")) ");
        E.setSize(576, 360); PrivatePanel.add(E);
    }
    public void UpdateParticipations(){
        listeEvenement E=new listeEvenement(IdUser,"-","select * from event where IDEvent in (select IDEvent from participations where IDEmp = '"+IdUser+"')");
        E.setSize(576, 360); 
        ParticipationsPanel.add(E);
    }
    public void UpdateMineDirector(){
        listeEvenement E=new listeEvenement(IdUser,"*","select *  from event  where IDOrg = '"+IdUser+"'");
       E.setSize(576, 360);
       MinePanel.add(E);
    }
    public void UpdateMine(){
        listeEvenement E=new listeEvenement(IdUser,"Modifier","select * from event e,participations p where (e.IDEvent = p.IDEvent and IDOrg = "+IdUser+"); ");
       E.setSize(576, 360);
       MinePanel.add(E);
    }
    public void Actualiser(){
        EspaceDirecteur I=new EspaceDirecteur(IdUser);
        I.setSize(910, 700);
        I.setVisible(true);
        this.setVisible(false);
        SwingUtilities.getWindowAncestor(this).add(I);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EspaceChef1 = new javax.swing.JPanel();
        AffichagePane = new javax.swing.JTabbedPane();
        TousPanel = new javax.swing.JPanel();
        PublicPanel = new javax.swing.JPanel();
        PrivatePanel = new javax.swing.JPanel();
        ParticipationsPanel = new javax.swing.JPanel();
        MinePanel = new javax.swing.JPanel();
        DiscoChef1 = new javax.swing.JButton();
        CreatEventButton = new javax.swing.JButton();
        Actualiser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        EspaceChef1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TousPanelLayout = new javax.swing.GroupLayout(TousPanel);
        TousPanel.setLayout(TousPanelLayout);
        TousPanelLayout.setHorizontalGroup(
            TousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        TousPanelLayout.setVerticalGroup(
            TousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Tous", TousPanel);

        javax.swing.GroupLayout PublicPanelLayout = new javax.swing.GroupLayout(PublicPanel);
        PublicPanel.setLayout(PublicPanelLayout);
        PublicPanelLayout.setHorizontalGroup(
            PublicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        PublicPanelLayout.setVerticalGroup(
            PublicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Publics", PublicPanel);

        javax.swing.GroupLayout PrivatePanelLayout = new javax.swing.GroupLayout(PrivatePanel);
        PrivatePanel.setLayout(PrivatePanelLayout);
        PrivatePanelLayout.setHorizontalGroup(
            PrivatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        PrivatePanelLayout.setVerticalGroup(
            PrivatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Privés", PrivatePanel);

        javax.swing.GroupLayout ParticipationsPanelLayout = new javax.swing.GroupLayout(ParticipationsPanel);
        ParticipationsPanel.setLayout(ParticipationsPanelLayout);
        ParticipationsPanelLayout.setHorizontalGroup(
            ParticipationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        ParticipationsPanelLayout.setVerticalGroup(
            ParticipationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Mes participations", ParticipationsPanel);

        javax.swing.GroupLayout MinePanelLayout = new javax.swing.GroupLayout(MinePanel);
        MinePanel.setLayout(MinePanelLayout);
        MinePanelLayout.setHorizontalGroup(
            MinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        MinePanelLayout.setVerticalGroup(
            MinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        AffichagePane.addTab("Mes événements", MinePanel);

        DiscoChef1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        DiscoChef1.setText("Déconnexion");
        DiscoChef1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscoChef1ActionPerformed(evt);
            }
        });

        CreatEventButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        CreatEventButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\icon_add_event.png")); // NOI18N
        CreatEventButton.setText("Créer un événement");
        CreatEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatEventButtonActionPerformed(evt);
            }
        });

        Actualiser.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Actualiser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\actualiser.png")); // NOI18N
        Actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EspaceChef1Layout = new javax.swing.GroupLayout(EspaceChef1);
        EspaceChef1.setLayout(EspaceChef1Layout);
        EspaceChef1Layout.setHorizontalGroup(
            EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(EspaceChef1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AffichagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addComponent(Actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(DiscoChef1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CreatEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EspaceChef1Layout.setVerticalGroup(
            EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspaceChef1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AffichagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EspaceChef1Layout.createSequentialGroup()
                        .addGroup(EspaceChef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiscoChef1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137)
                        .addComponent(CreatEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarah LOTFI\\Documents\\NetBeansProjects\\Event-management\\images\\kolna.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EspaceChef1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspaceChef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DiscoChef1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscoChef1ActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        JOptionPane.showMessageDialog(null ,"Au revoir!! BOSS " );
        GUI G=new GUI();
        Authentify A=new Authentify();
        A.setSize(1300, 500);
        G.add(A);
        G.setSize(600, 559);
        G.setVisible(true);
    }//GEN-LAST:event_DiscoChef1ActionPerformed

    private void CreatEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatEventButtonActionPerformed
        GUI G=new GUI();
        CreateEvent C=new CreateEvent(IdUser);
        C.setSize(478, 650);
        G.add(C);
        G.setSize(478, 650); G.setLocationRelativeTo(null);
        G.setVisible(true);
    }//GEN-LAST:event_CreatEventButtonActionPerformed

    private void ActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualiserActionPerformed
       Actualiser();
    }//GEN-LAST:event_ActualiserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualiser;
    private javax.swing.JTabbedPane AffichagePane;
    private javax.swing.JButton CreatEventButton;
    private javax.swing.JButton DiscoChef1;
    private javax.swing.JPanel EspaceChef1;
    private javax.swing.JPanel MinePanel;
    private javax.swing.JPanel ParticipationsPanel;
    private javax.swing.JPanel PrivatePanel;
    private javax.swing.JPanel PublicPanel;
    private javax.swing.JPanel TousPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
