package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import event.management.Employe;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import jdbc.Connexion;

/**
 *
 * @author Nada
 */
public class Evenement extends javax.swing.JPanel {
    private int IdUser;
    /**
     * Creates new form Guiii
     */
    Connexion con = new Connexion();
    Connection Maconnexion;
    public Evenement(int Id, String X) {
        initComponents();
        Maconnexion = con.getMaconnexion();
        IdUser=Id;
         this.Plus.setName(X);
        this.setSize(400,200);
        Desc.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Lieu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Plus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Org = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(300, 300));

        Titre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Titre.setText("Titre");

        Date.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        Date.setText("Date");

        Lieu.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        Lieu.setText("Lieu");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        jLabel4.setText("Le : ");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        jLabel5.setText("à : ");

        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        jLabel7.setText("Organisé par : ");

        Org.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        Org.setText("Org");

        jScrollPane2.setMaximumSize(new java.awt.Dimension(400, 400));

        Desc.setColumns(17);
        Desc.setLineWrap(true);
        Desc.setRows(5);
        Desc.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jScrollPane2.setViewportView(Desc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addComponent(Date)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lieu))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Org)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Plus)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(Lieu)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Org)
                    .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        Employe E=new Employe();
        switch(Plus.getText())
        {
            case "+" :E.Inscrire(IdUser, Integer.parseInt(Plus.getName()));break ;
            case "-" :E.Desincrire(IdUser, Integer.parseInt(Plus.getName()));break;
            case "Modifier" : CreateEvent Ev = new CreateEvent(IdUser , Plus.getName());
            GUI G = new GUI();
            G.setSize(300,500);
            Ev.setSize(300,500);
            Ev.setButton("Modifier");
            Ev.setLabel("Modifier");
            Statement St ;
            ResultSet Rs =null ;
            try {
            St=Maconnexion.createStatement();          
            Rs=St.executeQuery("select * from event where IDEvent = '"+Plus.getName()+"'");
            if(Rs.first())
            {
                Ev.setTitre(Rs.getString(2));                
                Ev.setType(Rs.getString(8));
                Ev.setLieu(Rs.getString(6));
                Ev.setSecteur(Rs.getString(3));
                Ev.setTheme(Rs.getString(4));
                Ev.setDescription(Rs.getString(7));
                Ev.setDate(Rs.getDate(5));
                Ev.setDeptPanel(Integer.parseInt(Plus.getName()));
                G.add(Ev);
                G.setVisible(true);                
            }                            
        
        } catch (SQLException ex) {
            Logger.getLogger(listeEvenement.class.getName()).log(Level.SEVERE, null, ex);
        }
            break;
            default :break;
        }
        
    }//GEN-LAST:event_PlusActionPerformed
    public void setName(String X)
    {
        Plus.setName(X);
    }
    public void setTitre(String X)
    {
        Titre.setText(X);
    }
    public void setDate(String X)
    {
        Date.setText(X);
    }
   public void setLieu(String X)
    {
        Lieu.setText(X);
    }
    public void setDesc(String X)
    {
        Desc.setText(X);
    }
    public void setOrg(String X)
    {
        Org.setText(X);
    }
    public void setMoins()
    {
        Plus.setText("-");
    }
    public void setPlus()
    {
        Plus.setText("+");
    }
    public void setModif()
    {
        Plus.setText("Modifier");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JTextArea Desc;
    private javax.swing.JLabel Lieu;
    private javax.swing.JLabel Org;
    private javax.swing.JButton Plus;
    private javax.swing.JLabel Titre;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
