package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.GridLayout;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import jdbc.Connexion;

/**
 *
 * @author Nada
 */
public class listeEvenement extends javax.swing.JPanel {

    /**
     * Creates new form listeEvenement
     */
    Connexion con = new Connexion();
    Connection Maconnexion;
    JPanel Panel = new JPanel();
    public listeEvenement(int Id, String op ,String Req) {
        initComponents();
        Maconnexion = con.getMaconnexion();
        Statement St , St2;
        ResultSet Rs1 , Rs2 ;
        this.setSize(400,300);
        Panel.setLayout(new GridLayout(0,1));  
        
        
        try {
            St=Maconnexion.createStatement();
            St2=Maconnexion.createStatement();
            Rs1=St.executeQuery(Req);
            if(Rs1.first())
            {
                do{
                    Evenement Event = new Evenement(Id , Rs1.getString(1));
                    switch(op)
                    {
                        case "+" : Event.setPlus();break;
                        case "-" : Event.setMoins(); break ;
                        case "*" : Event.setModif();break ;
                        default : break ;                        
                    }
                    Event.setTitre(Rs1.getString(2));
                    Event.setDate(Rs1.getString(5));
                    Event.setLieu(Rs1.getString(6));
                    Event.setDesc(Rs1.getString(7));                    
                    Rs2=St2.executeQuery("select Nom , Prenom from employe where ID = '"+Rs1.getString(9)+"'");
                    if(Rs2.first()){Event.setOrg(Rs2.getString(1)+" "+Rs2.getString(2));}
                    Panel.add(Event);
                }while(Rs1.next());
                JScrollPane pane = new JScrollPane(Panel);
                pane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
                pane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                pane.setBounds(50, 30, 350, 150);                
                this.add(pane);
                Maconnexion.close();
            }
            else
            {
               JOptionPane.showMessageDialog(null ,"Aucun Evenement a afficher " ,"Warning",JOptionPane.WARNING_MESSAGE);            
            }                            
        
        } catch (SQLException ex) {
            Logger.getLogger(listeEvenement.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
